routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/', ['uses' => 'HomeController@index', 'as' => 'front.home.index']);


Route::get('/kompanija', ['uses' => 'HomeController@company', 'as' => 'front.company.index']);
Route::get('/kompanija/{slug}', ['uses' => 'HomeController@showCompany', 'as' => 'front.company.show']);

Route::get('/proizvodi', ['uses' => 'HomeController@products', 'as' => 'front.product.index']);
Route::get('/proizvodi/{cat}', ['uses' => 'HomeController@productList', 'as' => 'front.product.list']);
Route::get('/proizvodi/{cat}/{slug}', ['uses' => 'HomeController@productShow', 'as' => 'front.product.show']);

Route::get('/rental', ['uses' => 'HomeController@rental', 'as' => 'front.rental.list']);
Route::get('/rental/{slug}', ['uses' => 'HomeController@showRental', 'as' => 'front.rental.show']);

Route::get('/polovne-masine', ['uses' => 'HomeController@used', 'as' => 'front.used.list']);
Route::get('/polovne-masine/{slug}', ['uses' => 'HomeController@showUsed', 'as' => 'front.used.show']);

Route::get('/servis-i-delovi', ['uses' => 'HomeController@showService', 'as' => 'front.service.show']);

Route::get('/vesti', ['uses' => 'HomeController@post', 'as' => 'front.post.index']);
Route::get('/vesti/{slug}', ['uses' => 'HomeController@showPost', 'as' => 'front.post.show']);

Route::get('/galerija', ['uses' => 'HomeController@gallery', 'as' => 'front.gallery.index']);
Route::get('/kontakt', ['uses' => 'HomeController@contact', 'as' => 'front.contact.index']);
Route::get('/zaposlenje', ['uses' => 'HomeController@career', 'as' => 'front.career.index']);

Route::post('/send', ['uses' => 'HomeController@contactUs', 'as' => 'front.contact.send']);

// Route::get('/proizvodi', ['uses' => 'HomeController@products', 'as' => 'front.product.index']);


Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'auth.login']);
    Route::post('/login', ['uses' => 'AuthController@postLogin', 'as' => 'auth.post-login']);
    Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'auth.logout']);
    
    Route::group(['middleware' => 'auth.admin'], function () {
        Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard.index']);
        
        Route::post('/administrator/change-status', ['uses' => 'AdministratorController@changeState', 'as' => 'administrator.change-status']);
        Route::resource('administrator','AdministratorController');
        
        Route::post('/slider/change-status', ['uses' => 'SliderController@changeState', 'as' => 'slider.change-status']);
        Route::put('/slider/reorder', ['uses' => 'SliderController@reorder', 'as' => 'slider.reorder']);
        Route::resource('slider','SliderController');
        
        Route::post('/post/change-status', ['uses' => 'PostController@changeState', 'as' => 'post.change-status']);
        Route::put('/post/reorder', ['uses' => 'PostController@reorder', 'as' => 'post.reorder']);
        Route::post('/post/slugify', ['uses' => 'PostController@slugify', 'as' => 'post.slugify']);
        Route::resource('post', 'PostController');
        
        Route::post('/post-photo/{id}', ['uses' => 'PostPhotoController@store', 'as' => 'post-photo.store']);
        Route::put('/post-photo/change-status', ['uses' => 'PostPhotoController@changeState', 'as' => 'post-photo.change-status']);
        Route::put('/post-photo/reorder', ['uses' => 'PostPhotoController@reorder', 'as' => 'post-photo.reorder']);
        Route::delete('/post-photo/{id}', ['uses' => 'PostPhotoController@destroy', 'as' => 'post-photo.destroy']);
        
        Route::post('/post-category/change-status', ['uses' => 'PostCategoryController@changeState', 'as' => 'post-category.change-status']);
        Route::put('/post-category/reorder', ['uses' => 'PostCategoryController@reorder', 'as' => 'post-category.reorder']);
        Route::post('/post-category/slugify', ['uses' => 'PostCategoryController@slugify', 'as' => 'post-category.slugify']);
        Route::resource('post-category', 'PostCategoryController');
        
        Route::post('/product/change-status', ['uses' => 'ProductController@changeState', 'as' => 'product.change-status']);
        Route::put('/product/reorder', ['uses' => 'ProductController@reorder', 'as' => 'product.reorder']);
        Route::post('/product/slugify', ['uses' => 'ProductController@slugify', 'as' => 'product.slugify']);
        Route::resource('product', 'ProductController');
        
        Route::post('/specification/change-status', ['uses' => 'SpecificationController@changeState', 'as' => 'specification.change-status']);
        Route::resource('specification', 'SpecificationController');

        Route::post('/product-photo/{id}', ['uses' => 'ProductPhotoController@store', 'as' => 'product-photo.store']);        
        Route::put('/product-photo/change-status', ['uses' => 'ProductPhotoController@changeState', 'as' => 'product-photo.change-status']);
        Route::put('/product-photo/reorder', ['uses' => 'ProductPhotoController@reorder', 'as' => 'product-photo.reorder']);
        Route::delete('/product-photo/{id}', ['uses' => 'ProductPhotoController@destroy', 'as' => 'product-photo.destroy']);


        Route::post('/product-category/change-status', ['uses' => 'ProductCategoryController@changeState', 'as' => 'product-category.change-status']);
        Route::put('/product-category/reorder', ['uses' => 'ProductCategoryController@reorder', 'as' => 'product-category.reorder']);
        Route::post('/product-category/slugify', ['uses' => 'ProductCategoryController@slugify', 'as' => 'product-category.slugify']);
        Route::resource('product-category', 'ProductCategoryController');
        
        Route::post('/product-subcategory/change-status', ['uses' => 'ProductSubcategoryController@changeState', 'as' => 'product-subcategory.change-status']);
        Route::put('/product-subcategory/reorder', ['uses' => 'ProductSubcategoryController@reorder', 'as' => 'product-subcategory.reorder']);
        Route::post('/product-subcategory/slugify', ['uses' => 'ProductSubcategoryController@slugify', 'as' => 'product-subcategory.slugify']);
        Route::resource('product-subcategory', 'ProductSubcategoryController');
        
        Route::post('/associate/change-status', ['uses' => 'AssociateController@changeState', 'as' => 'associate.change-status']);
        Route::put('/associate/reorder', ['uses' => 'AssociateController@reorder', 'as' => 'associate.reorder']);
        Route::post('/associate/slugify', ['uses' => 'AssociateController@slugify', 'as' => 'associate.slugify']);
        Route::resource('associate', 'AssociateController');
        
        
        Route::post('/gallery/change-status', ['uses' => 'GalleryController@changeState', 'as' => 'gallery.change-status']);
        Route::post('/gallery/slugify', ['uses' => 'GalleryController@slugify', 'as' => 'gallery.slugify']);
        Route::resource('gallery', 'GalleryController');


        Route::post('/gallery-photo/{id}', ['uses' => 'GalleryPhotoController@store', 'as' => 'gallery-photo.store']);
        Route::put('/gallery-photo/change-status', ['uses' => 'GalleryPhotoController@changeState', 'as' => 'gallery-photo.change-status']);
        Route::put('/gallery-photo/reorder', ['uses' => 'GalleryPhotoController@reorder', 'as' => 'gallery-photo.reorder']);
        Route::delete('/gallery-photo/{id}', ['uses' => 'GalleryPhotoController@destroy', 'as' => 'gallery-photo.destroy']);
        
        Route::post('/service/change-status', ['uses' => 'ServiceController@changeState', 'as' => 'service.change-status']);
        Route::put('/service/reorder', ['uses' => 'ServiceController@reorder', 'as' => 'service.reorder']);
        Route::resource('service', 'ServiceController');

    });
});

app/Gallery.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Gallery extends Model
{
    protected $table = 'galleries';

    protected $fillable = ['title', 'slug', 'excerpt', 'order', 'is_active'];

    public $timestamps = false;

    public function photos()
    {
        return $this->hasMany('App\GalleryPhoto');
    }
}

app/Http/Controllers/Admin/GalleryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Repositories\Gallery\GalleryInterface;

class GalleryController extends BaseController
{

    protected $gallery;

    public function __construct(GalleryInterface $gallery)
    {
        $this->gallery = $gallery;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.gallery.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        // $file = $request->file('file');
        // if (in_array($file->guessExtension(), ['jpeg', 'png'])) {
        //     $data['filename'] = $media->upload($file, config('settings.image.gallery'));
        // }
        $gallery = $this->gallery->create($data);
        return redirect(route('admin.gallery.edit', $gallery->id));
        \flash('Galerija je uspešno kreirana')->success();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $gallery = $this->gallery->find($id);
        return view('admin.gallery.edit', compact('gallery'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $gallery = $this->gallery->find($id);
        $data = $request->all();

        // $data['filename'] = $media->upload($request->file('file'), config('settings.image.gallery'));
        // if ($data['filename']) {
            // $media->delete($this->gallery->find($id)->filename, config('settings.image.gallery'));
        // }
        $this->gallery->update($id, $data);

        \flash('Galerija je uspešno izmenjen')->success();
        return redirect(route('admin.gallery.edit', $gallery->id));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->deleteItem($this->gallery, $id);
    }

    public function changeState(Request $request)
    {
        return $this->changeStatus($this->gallery, $request->id);
    }

    public function slugify(Request $request)
    {
        return ['slug' => $this->gallery->slugify($request->all())];
    }

    public function reorder(Request $request)
    {
        if ($request->get('sort_item')) {
            foreach ($request->get('sort_item') as $index => $itemId) {
                $this->gallery->setOrder($itemId, $index);
            }
            return ['status' => 'success'];
        }
    }
}

resources/views/admin/gallery/create.blade.php
@extends('admin.layout.template')

@section('page-heading', 'Galerija')

@section('content')
    <div class="panel-heading">
        <h4>Nova galerija</h4>
        <div class="options">

        </div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" action="{{ route('admin.gallery.store') }}" data-resource="gallery" method="post" enctype="multipart/form-data">                
                {{ csrf_field() }}
                <div class="form-group">
                    <div class="row">
                        <label for="title" class="col-sm-2 control-label">Naziv</label>
                        <div class="col-sm-6">
                            <textarea class="form-control slugify" id="title" name="title"></textarea>
                        </div>
                        <div class="col-sm-3">
                            <p class="help-block"></p>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label for="slug" class="col-sm-2 control-label">Slug</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="slug" name="slug">
                        </div>
                        <div class="col-sm-3">
                            <p class="help-block"></p>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">    
                        <label for="excerpt" class="col-sm-2 control-label">Uvod</label>
                        <div class="col-sm-6">
                            <textarea class="form-control" id="excerpt" name="excerpt"></textarea>
                        </div>
                        <div class="col-sm-3">
                            <p class="help-block"></p>
                        </div>
                    </div>
                </div>
                {{--  <div class="form-group">
                    <div class="row">
                        <div class="col-sm-3 col-sm-offset-2">  
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="width: 360px; height: 200px;"></div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 360px; max-height: auto;"></div>
                                <div>
                                    <span class="btn btn-default btn-file"><span class="fileinput-new">Izaberi sliku</span><span class="fileinput-exists">Izmeni</span>
                                    <input type="file" name="file" accept="image/*"></span>
                                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Izbriši</a>
                                </div>
                            </div>
                        </div>
                        <div class"col-sm-3">
                            <label for="gallery_date" class="control-label">Datum objave:</label>
                            <input type="date" id="gallery_date" name="gallery_date">
                        </div>
                    </div>
                </div>  --}}
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-3">
                        <input type="hidden" name="is_active" value="0">
                        <div class="toggle toggle-success form-active"></div>
                    </div>
                    <div class="col-sm-3">
                        <button class="btn-primary btn">Snimi</button>                    
                    </div>
                </div>
        </form>
    </div>
@stop

resources/views/admin/gallery/edit.blade.php
@extends('admin.layout.template')

@section('page-heading', 'Galerija')

@section('content')
    <div class="panel-heading">
        
        {{--  <h4>Uredi gallery</h4>  --}}
        <div class="options">
            <ul class="nav nav-tabs">
                <li class="active">
                    <a href="#form" data-toggle="tab">Forma</a>
                </li>
                <li>
                    <a href="#packshots" data-toggle="tab">Fotografije</a>
                </li>
            </ul>    
        </div>
    </div>
    <div class="panel-body">
        <div class="tab-content">
            <div class="tab-pane active" id="form">
                <form class="form-horizontal" action="{{ route('admin.gallery.update', $gallery->id) }}" data-resource="gallery" method="post" enctype="multipart/form-data">                
                        {{ csrf_field() }}
                        {{ method_field('put') }}
        
                        <div class="form-group">
                            <div class="row">
                                <label for="title" class="col-sm-2 control-label">Naziv</label>
                                <div class="col-sm-6">
                                    <textarea class="form-control slugify" id="title" name="title">{{ $gallery->title }}</textarea>
                                </div>
                                <div class="col-sm-3">
                                    <p class="help-block"></p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <label for="slug" class="col-sm-2 control-label">Slug</label>
                                <div class="col-sm-6">
                                    <input type="text" class="form-control" id="slug" name="slug" value="{{ $gallery->slug }}">
                                </div>
                                <div class="col-sm-3">
                                    <p class="help-block"></p>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="row">    
                                <label for="excerpt" class="col-sm-2 control-label">Uvod</label>
                                <div class="col-sm-6">
                                    <textarea class="form-control" id="excerpt" name="excerpt">{{ $gallery->excerpt }}</textarea>
                                </div>
                                <div class="col-sm-3">
                                    <p class="help-block"></p>
                                </div>
                            </div>
                        </div>
                        {{--  <div class="form-group">
                            <div class="row">
                                <div class="col-sm-3 col-sm-offset-2">  
                                    <div class="fileinput fileinput-exists" data-provides="fileinput">
                                        <div class="fileinput-new thumbnail" style="width: 360px; height: 200px;"></div>
                                        <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 360px; max-height: auto;">
                                            <img src="{{ config('settings.image.gallery.upload_dir').$gallery->filename }}" class="img-responsive" alt="">
                                        </div>
                                        <div>
                                            <span class="btn btn-default btn-file"><span class="fileinput-new">Izaberi sliku</span><span class="fileinput-exists">Izmeni</span>
                                            <input type="file" name="file" accept="image/*"></span>
                                            <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Izbriši</a>
                                        </div>
                                    </div>
                                </div>
                                <div class"col-sm-3">
                                    <label for="gallery_date" class="control-label">Datum objave:</label>
                                    <input type="date" id="gallery_date" name="gallery_date" value="{{ date('Y-m-d', strtotime($gallery->created_at)) }}">
                                </div>
                            </div>
                        </div>  --}}
                        <div class="form-group">
                            <div class="col-md-4 col-md-offset-3">
                                <input type="hidden" name="is_active" value="{{ $gallery->is_active }}">
                                <div class="toggle toggle-success {{ $gallery->is_active ? 'active' : '' }} form-active" title="Status" data-id="{{ $gallery->id }}"></div>
                            </div>
                            <div class="col-sm-3">
                                <button class="btn-primary btn">Snimi</button>                    
                            </div>
                        </div>
                </form>
            </div>
            <div class="tab-pane" id="packshots">
                {{--  <form action="#" class="fileupload-photo" >  --}}
                    <form class="fileupload-photo" action="{{ route('admin.gallery-photo.store', $gallery->id) }}" method="POST" enctype="multipart/form-data">
                        <span class="btn btn-success fileinput-button photo-upload-button">
                            <h2><i class="fa fa-cloud-upload"></i>Spustite fajlove ovde</h2>
                            <h4>ili kliknite</h4>
                            <!-- The file input field used as target for the file upload widget -->
                            <input type="file" name="files[]" multiple>
                        </span>
                    </form>
                    <br>
                    <br>
                    <!-- The global progress bar -->
                    <div class="progress-bar progress-bar-success col-md-12" role="progressbar" aria-valuenow="" aria-valuemin="0" aria-valuemax="100" style="">
                        <span class="sr-only"></span>
                    </div>
                    <div class="col-md-12 errors-wrapper"></div>
            
                    <ul class="gallery images gallery uploaded list-unstyled col-sm-12" data-type="1">
                        @if($gallery->photos)
                        @foreach ($gallery->photos as $photo)
                        <li class="image" data-resource="gallery-photo" data-name="" data-id="{{ $photo->id }}" id="file-{{ $photo->id }}">
                            <a class="file-thumb {{ !$photo['is_active'] ? 'inactive' : ''}}" href="/uploads/gallery/images/{{ $photo->filename }}" data-lightbox="photos">
                                <img src="/uploads/gallery/images/{{ $photo->filename }}" width="230"></a>
                            </a>
                            <div class="toggle toggle-success {{ $photo->is_active ? 'active' : '' }} file-active" title="Status"></div>
                            <button type="button"  class="btn btn-danger-alt remove-file"><i class="fa fa-times"></i></button>
                        </li>
                        @endforeach
                        @endif
                    </ul>
                
                {{--  </form>  --}}
            </div>
        </div>
       
    </div>
@stop