routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });


Route::get('/', ['uses' => 'HomeController@index', 'as' => 'front.home.index']);


Route::get('/kompanija', ['uses' => 'HomeController@company', 'as' => 'front.company.index']);
Route::get('/kompanija/{slug}', ['uses' => 'HomeController@showCompany', 'as' => 'front.company.show']);

Route::get('/proizvodi', ['uses' => 'HomeController@products', 'as' => 'front.product.index']);
Route::get('/proizvodi/{cat}', ['uses' => 'HomeController@productList', 'as' => 'front.product.list']);
Route::get('/proizvodi/{cat}/{slug}', ['uses' => 'HomeController@productShow', 'as' => 'front.product.show']);

Route::get('/rental', ['uses' => 'HomeController@rental', 'as' => 'front.rental.list']);
Route::get('/rental/{slug}', ['uses' => 'HomeController@showRental', 'as' => 'front.rental.show']);

Route::get('/polovne-masine', ['uses' => 'HomeController@used', 'as' => 'front.used.list']);
Route::get('/polovne-masine/{slug}', ['uses' => 'HomeController@showUsed', 'as' => 'front.used.show']);

Route::get('/servis-i-delovi', ['uses' => 'HomeController@showService', 'as' => 'front.service.show']);

Route::get('/vesti', ['uses' => 'HomeController@post', 'as' => 'front.post.index']);
Route::get('/vesti/{slug}', ['uses' => 'HomeController@showPost', 'as' => 'front.post.show']);

Route::get('/galerija', ['uses' => 'HomeController@gallery', 'as' => 'front.gallery.index']);
Route::get('/kontakt', ['uses' => 'HomeController@contact', 'as' => 'front.contact.index']);
Route::get('/zaposlenje', ['uses' => 'HomeController@career', 'as' => 'front.career.index']);

Route::post('/send', ['uses' => 'HomeController@contactUs', 'as' => 'front.contact.send']);

// Route::get('/proizvodi', ['uses' => 'HomeController@products', 'as' => 'front.product.index']);


Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function() {
    Route::get('/login', ['uses' => 'AuthController@login', 'as' => 'auth.login']);
    Route::post('/login', ['uses' => 'AuthController@postLogin', 'as' => 'auth.post-login']);
    Route::get('/logout', ['uses' => 'AuthController@logout', 'as' => 'auth.logout']);
    
    Route::group(['middleware' => 'auth.admin'], function () {
        Route::get('/', ['uses' => 'DashboardController@index', 'as' => 'dashboard.index']);
        
        Route::post('/administrator/change-status', ['uses' => 'AdministratorController@changeState', 'as' => 'administrator.change-status']);
        Route::resource('administrator','AdministratorController');
        
        Route::post('/slider/change-status', ['uses' => 'SliderController@changeState', 'as' => 'slider.change-status']);
        Route::put('/slider/reorder', ['uses' => 'SliderController@reorder', 'as' => 'slider.reorder']);
        Route::resource('slider','SliderController');
        
        Route::post('/post/change-status', ['uses' => 'PostController@changeState', 'as' => 'post.change-status']);
        Route::put('/post/reorder', ['uses' => 'PostController@reorder', 'as' => 'post.reorder']);
        Route::post('/post/slugify', ['uses' => 'PostController@slugify', 'as' => 'post.slugify']);
        Route::resource('post', 'PostController');
        
        Route::post('/post-photo/{id}', ['uses' => 'PostPhotoController@store', 'as' => 'post-photo.store']);
        Route::put('/post-photo/change-status', ['uses' => 'PostPhotoController@changeState', 'as' => 'post-photo.change-status']);
        Route::put('/post-photo/reorder', ['uses' => 'PostPhotoController@reorder', 'as' => 'post-photo.reorder']);
        Route::delete('/post-photo/{id}', ['uses' => 'PostPhotoController@destroy', 'as' => 'post-photo.destroy']);
        
        Route::post('/post-category/change-status', ['uses' => 'PostCategoryController@changeState', 'as' => 'post-category.change-status']);
        Route::put('/post-category/reorder', ['uses' => 'PostCategoryController@reorder', 'as' => 'post-category.reorder']);
        Route::post('/post-category/slugify', ['uses' => 'PostCategoryController@slugify', 'as' => 'post-category.slugify']);
        Route::resource('post-category', 'PostCategoryController');
        
        Route::post('/product/change-status', ['uses' => 'ProductController@changeState', 'as' => 'product.change-status']);
        Route::put('/product/reorder', ['uses' => 'ProductController@reorder', 'as' => 'product.reorder']);
        Route::post('/product/slugify', ['uses' => 'ProductController@slugify', 'as' => 'product.slugify']);
        Route::resource('product', 'ProductController');
        
        Route::post('/specification/change-status', ['uses' => 'SpecificationController@changeState', 'as' => 'specification.change-status']);
        Route::resource('specification', 'SpecificationController');

        Route::post('/product-photo/{id}', ['uses' => 'ProductPhotoController@store', 'as' => 'product-photo.store']);        
        Route::put('/product-photo/change-status', ['uses' => 'ProductPhotoController@changeState', 'as' => 'product-photo.change-status']);
        Route::put('/product-photo/reorder', ['uses' => 'ProductPhotoController@reorder', 'as' => 'product-photo.reorder']);
        Route::delete('/product-photo/{id}', ['uses' => 'ProductPhotoController@destroy', 'as' => 'product-photo.destroy']);


        Route::post('/product-category/change-status', ['uses' => 'ProductCategoryController@changeState', 'as' => 'product-category.change-status']);
        Route::put('/product-category/reorder', ['uses' => 'ProductCategoryController@reorder', 'as' => 'product-category.reorder']);
        Route::post('/product-category/slugify', ['uses' => 'ProductCategoryController@slugify', 'as' => 'product-category.slugify']);
        Route::resource('product-category', 'ProductCategoryController');
        
        Route::post('/product-subcategory/change-status', ['uses' => 'ProductSubcategoryController@changeState', 'as' => 'product-subcategory.change-status']);
        Route::put('/product-subcategory/reorder', ['uses' => 'ProductSubcategoryController@reorder', 'as' => 'product-subcategory.reorder']);
        Route::post('/product-subcategory/slugify', ['uses' => 'ProductSubcategoryController@slugify', 'as' => 'product-subcategory.slugify']);
        Route::resource('product-subcategory', 'ProductSubcategoryController');
        
        Route::post('/associate/change-status', ['uses' => 'AssociateController@changeState', 'as' => 'associate.change-status']);
        Route::put('/associate/reorder', ['uses' => 'AssociateController@reorder', 'as' => 'associate.reorder']);
        Route::post('/associate/slugify', ['uses' => 'AssociateController@slugify', 'as' => 'associate.slugify']);
        Route::resource('associate', 'AssociateController');
        
        
        Route::post('/gallery/change-status', ['uses' => 'GalleryController@changeState', 'as' => 'gallery.change-status']);
        Route::post('/gallery/slugify', ['uses' => 'GalleryController@slugify', 'as' => 'gallery.slugify']);
        Route::resource('gallery', 'GalleryController');


        Route::post('/gallery-photo/{id}', ['uses' => 'GalleryPhotoController@store', 'as' => 'gallery-photo.store']);
        Route::put('/gallery-photo/change-status', ['uses' => 'GalleryPhotoController@changeState', 'as' => 'gallery-photo.change-status']);
        Route::put('/gallery-photo/reorder', ['uses' => 'GalleryPhotoController@reorder', 'as' => 'gallery-photo.reorder']);
        Route::delete('/gallery-photo/{id}', ['uses' => 'GalleryPhotoController@destroy', 'as' => 'gallery-photo.destroy']);
        
        Route::post('/service/change-status', ['uses' => 'ServiceController@changeState', 'as' => 'service.change-status']);
        Route::put('/service/reorder', ['uses' => 'ServiceController@reorder', 'as' => 'service.reorder']);
        Route::resource('service', 'ServiceController');

    });
});

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $table = 'products';

    protected $fillable = ['title', 'product_subcategory_id', 'type', 'slug', 'text', 'filename', 'attachment', 'order', 'is_active', 'attachment_label', 'created_at'];

    public $timestamps = false;

    // public function photos()
    // {
    //     return $this->hasMany(Photo::class);
    // }
    
    public function productSubcategory()
    {
        return $this->belongsTo('App\ProductSubcategory');
    }

    public function photos()
    {
        return $this->hasMany('App\ProductPhoto');
    }

    public function specifications()
    {
        return $this->hasMany('App\Specification');
    }

    public function relatedSpecifications()
    {
        return $this->belongsToMany('App\Specification');
    } 

}

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Requests\ProductRequest;
use App\Services\File\Image as ImageService;
use App\Services\File\Document as DocumentService;
use App\Repositories\Product\ProductInterface;
use App\Repositories\ProductSubcategory\ProductSubcategoryInterface as Subcategory;

class ProductController extends BaseController
{
    protected $product;

    public function __construct(ProductInterface $product) {
        $this->product = $product;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $listArray = $this->product->all();
        return view('admin.product.index', compact('listArray'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Subcategory $subcategory)
    {
        
        $categories = $subcategory->getActive();
        
        return view('admin.product.create', compact('categories'));    
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ProductRequest $request, ImageService $media, DocumentService $document)
    {
        $data = $request->all();
        $file = $request->file('file');
        if (in_array($file->guessExtension(), ['jpeg', 'png'])) {
            $data['filename'] = $media->upload($file, config('settings.image.product'));
        }
        $data['attachment'] = $document->upload($request->file('attachment'), config('settings.file.product'));
        $product = $this->product->create($data);
        return redirect(route('admin.product.edit', $product->id));
        \flash('Proizvod je uspešno kreiran')->success();

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Subcategory $subcategory, $id)
    {
        $product = $this->product->find($id);
        $subcategories = $subcategory->getActive();
        return view('admin.product.edit', compact('product', 'subcategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ProductRequest $request, ImageService $media, DocumentService $document, $id)
    {
        $product = $this->product->find($id);
        $data = $request->all();

        $data['filename'] = $media->upload($request->file('file'), config('settings.image.product'));
        $data['attachment'] = $document->upload($request->file('attachment'), config('settings.file.product'));

        if ($data['filename']) {
            $media->delete($this->product->find($id)->filename, config('settings.image.product'));
        }

        if ($data['attachment']) {
            $media->delete($this->product->find($id)->filename, config('settings.file.product'));
        }

        $this->product->update($id, $data);

        \flash('Proizvod je uspešno izmenjen')->success();
        return redirect(route('admin.product.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        return $this->deleteItem($this->product, $id);
    }

    public function changeState(Request $request)
    {
        return $this->changeStatus($this->product, $request->id);
    }

    public function slugify(Request $request)
    {
        return ['slug' => $this->product->slugify($request->all())];
    }

    public function reorder(Request $request)
    {
        if ($request->get('sort_item')) {
            foreach ($request->get('sort_item') as $index => $itemId) {
                $this->product->setOrder($itemId, $index);
            }
            return ['status' => 'success'];
        }
    }
}

resources/views/admin/product/category/create.blade.php
@extends('admin.layout.template')

@section('page-heading', 'Kategorija proizvoda')

@section('content')
    <div class="panel-heading">
        <h4>Nova kategorija</h4>
        <div class="options">

        </div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" action="{{ route('admin.product-category.store') }}" data-resource="product-category" method="post" enctype="multipart/form-data">                
                {{ csrf_field() }}
                <div class="form-group">
                    <div class="row">
                        <label for="name" class="col-sm-2 control-label">Naslov</label>
                        <div class="col-sm-6">
                            <textarea class="form-control slugify" id="name" name="name"></textarea>
                        </div>
                        <div class="col-sm-3">
                            <p class="help-block">{{ $errors->first('name') }}</p>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label for="slug" class="col-sm-2 control-label">Slug</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="slug" name="slug">
                        </div>
                        <div class="col-sm-3">
                            <p class="help-block">{{ $errors->first('slug') }}</p>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <div class="col-sm-3 col-sm-offset-2">  
                            <div class="fileinput fileinput-new" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="width: 360px; height: 200px;"></div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 360px; max-height: auto;"></div>
                                <div>
                                    <span class="btn btn-default btn-file"><span class="fileinput-new">Izaberi sliku</span><span class="fileinput-exists">Izmeni</span>
                                    <input type="file" name="file" accept="image/*"></span>
                                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Izbriši</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4 col-md-offset-3">
                        <input type="hidden" name="is_active" value="0">
                        <div class="toggle toggle-success form-active"></div>
                    </div>
                    <div class="col-sm-3">
                        <button class="btn-primary btn">Snimi</button>                    
                    </div>
                </div>
        </form>
    </div>
@stop

resources/views/admin/product/category/edit.blade.php
@extends('admin.layout.template')

@section('page-heading', 'Kategorija')

@section('content')
    <div class="panel-heading">
        <h4>Uredi Kategoriju</h4>
        <div class="options">

        </div>
    </div>
    <div class="panel-body">
        <form class="form-horizontal" data-resource="product-category" action="{{ route('admin.product-category.update', $category->id) }}" method="post" enctype="multipart/form-data">
            <div class="col-md-6" >
                {{ csrf_field() }}
                {{ method_field('put') }}

                <div class="form-group">
                    <label for="name" class="col-sm-2 control-label">Naziv</label>
                    <div class="col-sm-6">
                        <textarea class="form-control slugify" id="name" name="name">{{ $category->name }}</textarea>
                    </div>
                    <div class="col-sm-3">
                        <p class="help-block">{{ $errors->first('name') }}</p>
                    </div>
                </div>
                <div class="form-group">
                    <div class="row">
                        <label for="slug" class="col-sm-2 control-label">Slug</label>
                        <div class="col-sm-6">
                            <input type="text" class="form-control" id="slug" name="slug" value="{{ $category->slug }}">
                        </div>
                        <div class="col-sm-3">
                            <p class="help-block">{{ $errors->first('file') }}</p>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <div class="col-sm-9">  
                        <div class="fileinput fileinput-exists" data-provides="fileinput">
                                <div class="fileinput-new thumbnail" style="width: 360px; height: 240px;"></div>
                                <div class="fileinput-preview fileinput-exists thumbnail" style="max-width: 360px; max-height:auto;">
                                    <img src="{{ config('settings.image.product-category.upload_dir').$category->filename }}" class="img-responsive" alt="">
                                </div>
                                <div>
                                    <span class="btn btn-default btn-file"><span class="fileinput-new">Izaberi sliku</span><span class="fileinput-exists">Izmeni</span>
                                    <input type="file" name="file" accept="image/*"></span>
                                    <a href="#" class="btn btn-default fileinput-exists" data-dismiss="fileinput">Izbriši</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-4">
                        <input type="hidden" name="is_active" value="0">
                        <div class="toggle toggle-success {{ $category->is_active ? 'active' : '' }} form-active" title="Status" data-id="{{ $category->id }}"></div>
                    </div>
                    <div class="col-sm-3">
                        <button class="btn-primary btn">Snimi</button>                    
                    </div>
                </div>
            </form>
    </div>
@stop

resources/views/admin/product/category/index.blade.php
@extends('admin.layout.template')

@section('page-heading', 'Kategorije')

@section('content')
    @include('flash::message')
    <div class="panel-heading">
        <h4>Kategorije proizvoda</h4>
        <div class="options">

        </div>
    </div>
    <div class="panel-body resource-container" data-resource="product-category" data-modal="Da li želiš da obrišeš kategoriju?">
        @if(count($listArray))
        <table class="table sortable">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Naslov</th>
                    {{--  <th>Datum objave</th>  --}}
                    <th class="text-center">Aktivan</th>
                    <th>Opcije</th>
                </tr>
            </thead>
            <tbody>
                    @foreach($listArray as $key => $item)
                    <tr data-id="{{ $item->id }}" id="item-{{ $item->id }}">
                        <td style="cursor: move;" class="bars"><i class="fa fa-bars"></i></td>
                        <td><a href="{{ route('admin.product-category.edit', $item->id) }}">{{ $item->name }}</a></td>
                        {{--  <td>{{ $item->created_at }}</td>  --}}
                        <td class="table-active">
                            <div class="toggle toggle-success {{ $item->is_active ? 'active' : '' }} table-ajax" title="Status" data-id="{{ $item->id }}"></div>
                        </td>
                        <td class="table-options">
                            <a href="{{ route('admin.product-category.edit', $item->id) }}" class="option-edit"><i class="fa fa-pencil"></i></a>
                            <a style="margin-left: 15px; cursor: pointer; color: red;" class="delete-item"><i class="fa fa-times"></i> </a>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <h3>Lista je trenutno prazna</h3>
        @endif
        </div>
@stop